[package]
name = "aqua"
version = "0.1.0"
authors = ["Robbie Straw <drbawb@fatalsyntax.com>"]

[dependencies]
aqua-web = { version = "0.1.0", path = "aqua-web" }
diesel = { version = "0.10", features = ["postgres"] }
diesel_codegen = { version = "0.10", features = ["postgres"] }
dotenv = "0.8"
env_logger = "0.3"
log = "0.3"
iron = "0.5"
handlebars = { version = "*", features = ["serde_type"] }
mime = "*"
mime_guess = "*"
params = "0.6"
r2d2 = "*"
r2d2-diesel = "*"
router = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "0.1"
