[package]
name = "aqua"
version = "0.1.0"
authors = ["Robbie Straw <drbawb@fatalsyntax.com>"]

[dependencies]
env_logger = "0.3"
log = "0.3"
iron = "0.5"
handlebars = { version = "*", features = ["serde_type"] }
mime = "*"
mime_guess = "*"
postgres = "0.13"
r2d2 = "*"
r2d2_postgres = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "0.1"
